dataset_path: "/working/colmap_ws/2right_gps"
output_dir: "/working/colmap_ws/2right_gps/SfM" #is taken as output dir for sparse reconstruction and input dir for dense reconstruction
pose_type: "GPS" # "tf": known pose reconstruction, "GPS": SfM pose estimator reconstruction
cameras: [camera_right(1s), camera_right(2s)] # cameras to reconstruct under dataset_path
matcher: "spatial" # "spatial" "exhaustive", "sequential". Sequential only for 1 camera because it would match last camera1 image with first camera2 image
SfM_multiple_models: True
use_gpu: True
PT_cycle: 10 # point refinement cycles for known pose reconstructions
reconstruction: "sparse" # "sparse", "dense", "both"
GPS_scalation_type: "enu" # plane, ecef, enu, enu-plane,enu-plane-unscaled, custom